# Generated by Django 2.1.4 on 2018-12-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Florarium_LinkerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('link', models.TextField()),
                ('alt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gift_LinkerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('link', models.TextField()),
                ('alt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Florarium_EmptyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('use_images', models.BooleanField()),
                ('caption', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('alt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Florarium_FullForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('use_images', models.BooleanField()),
                ('caption', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('alt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Gifts_ChristmasGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('use_images', models.BooleanField()),
                ('caption', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('alt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Gifts_Lamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('use_images', models.BooleanField()),
                ('caption', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('alt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Gifts_Souvenir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('use_images', models.BooleanField()),
                ('caption', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('alt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Gifts_VitrazhPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('use_images', models.BooleanField()),
                ('caption', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('alt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index_LinkerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('link', models.TextField()),
                ('alt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('use_images', models.BooleanField()),
                ('text', models.TextField()),
            ],
        ),
    ]
